sudo: true
language: ruby
addons:
  ssh_known_hosts: jacobshack.com
branches:
  only:
  - master
  - develop
before_install:
  - bundle install
script:
  - bundle exec jekyll build --destination $TRAVIS_BUILD_DIR/dest
deploy:
- provider: script
  skip_cleanup: true
  script: /bin/bash _deploy/deploy.sh
  on:
    branch: develop
