language: javascript
addons:
  ssh_known_hosts: jacobshack.com
branches:
  only:
  - master
  - develop
before_install:
  - openssl aes-256-cbc -K $encrypted_e99421f60ac1_key -iv $encrypted_e99421f60ac1_iv -in travis_deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ ngetahun@jacobshack.com:/var/www/jacobshack.com
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ ngetahun@jacobshack.com:/var/www/2017f.jacobshack.com
  on:
    branch: develop
