sudo: true
language: node_js
node_js:
  - "7.2"
addons:
  ssh_known_hosts: jacobshack.com
  apt:
    packages:
      - ruby
branches:
  only:
  - master
  - develop
cache:
  directories:
    - "node_modules"
  yarn: true
before_install:
  - openssl aes-256-cbc -K $encrypted_e99421f60ac1_key -iv $encrypted_e99421f60ac1_iv -in travis_deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - gem install compass
script:
  - npm install -g gulp-cli yarn
  - npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/* ngetahun@jacobshack.com:/home/ngetahun/jacobshack.com
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/* ngetahun@jacobshack.com:/home/ngetahun/www/2017f.jacobshack.com
  on:
    branch: develop
